version: '3'
services:
  frontend:
    image: stark07/frontend:latest  # Replace with your Docker Hub image name and tag
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - api

  auth:
    image: stark07/auth:latest  # Replace with your Docker Hub image name and tag
    ports:
      - "8000:5001"

  api:
    image: stark07/api:latest  # Replace with your Docker Hub image name and tag
    ports:
      - "5002:5002"
