version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - api

  auth:
    build: ./auth
    ports:
      - "5001:5001"

  api:
    build: ./api
    ports:
      - "5002:5002"
